#!/bin/bash
set -e

# Cadre - Uninstaller

INSTALL_DIR="${CADRE_DIR:-$HOME/.cadre-ai}"
CLAUDE_DIR="$HOME/.claude"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BOLD}Cadre - Uninstaller${NC}"
echo ""

# Check if installed
if [ ! -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Cadre is not installed at $INSTALL_DIR${NC}"
    exit 0
fi

echo -e "This will remove:"
echo -e "  - $INSTALL_DIR (framework, hooks, system bridge)"
echo -e "  - Installed agents from $CLAUDE_DIR/agents/"
echo -e "  - Installed commands from $CLAUDE_DIR/commands/"
echo -e "  - Installed skills from $CLAUDE_DIR/skills/"
echo -e "  - Generated CLAUDE.md"
echo ""
echo -e "${YELLOW}Your MCP server data (memory database, etc.) will NOT be deleted.${NC}"
echo ""

read -p "Are you sure? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy] ]]; then
    echo "Cancelled."
    exit 0
fi

# Stop system bridge daemon
if [ -f "$INSTALL_DIR/system-bridge/daemon.pid" ]; then
    PID=$(cat "$INSTALL_DIR/system-bridge/daemon.pid" 2>/dev/null)
    if [ -n "$PID" ]; then
        kill "$PID" 2>/dev/null || true
        echo -e "${GREEN}[✓]${NC} Stopped system bridge daemon"
    fi
fi

# Remove installed agents (only ones that came from cadre-ai)
POWERKIT_AGENTS=(
    orchestrator.md learning-agent.md agent-builder.md code-architect.md
    python-engineer.md fullstack-dev.md csharp-developer.md ml-engineer.md
    devops-agent.md code-simplifier.md project-manager.md prompt-engineer.md
    tech-scout.md market-analyst.md code-analyzer.yaml test-runner.yaml doc-scraper.yaml
)
for agent in "${POWERKIT_AGENTS[@]}"; do
    rm -f "$CLAUDE_DIR/agents/$agent"
done
echo -e "${GREEN}[✓]${NC} Removed agent definitions"

# Remove installed commands
POWERKIT_COMMANDS=(
    commit.md delegate.md background.md prime.md prime-feature.md prime-bug.md
    context.md memory.md voice.md status.md tasks.md review-and-fix.md
    fix-and-commit.md analyze-patterns.md system-bridge.md render.md
    resume.md pipeline.md skills.md skill-info.md use-skill.md list-skills.md
)
for cmd in "${POWERKIT_COMMANDS[@]}"; do
    rm -f "$CLAUDE_DIR/commands/$cmd"
done
echo -e "${GREEN}[✓]${NC} Removed slash commands"

# Remove installed skills
rm -f "$CLAUDE_DIR/skills/"*.skill 2>/dev/null
echo -e "${GREEN}[✓]${NC} Removed skill files"

# Remove generated CLAUDE.md (if it's ours)
if grep -q "Generated by Cadre" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
    rm -f "$CLAUDE_DIR/CLAUDE.md"
    echo -e "${GREEN}[✓]${NC} Removed generated CLAUDE.md"
fi

# Restore backup if available
LATEST_BACKUP=$(ls -td "$CLAUDE_DIR"/backup-* 2>/dev/null | head -1)
if [ -n "$LATEST_BACKUP" ] && [ -d "$LATEST_BACKUP" ]; then
    read -p "Restore backup from $LATEST_BACKUP? [Y/n]: " restore
    if [[ ! "$restore" =~ ^[Nn] ]]; then
        cp "$LATEST_BACKUP"/* "$CLAUDE_DIR/" 2>/dev/null || true
        echo -e "${GREEN}[✓]${NC} Restored backup"
    fi
fi

# Remove install directory
rm -rf "$INSTALL_DIR"
echo -e "${GREEN}[✓]${NC} Removed $INSTALL_DIR"

# Remove env var from shell rc
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    if [ -f "$rc" ]; then
        sed -i '/CADRE_DIR/d' "$rc" 2>/dev/null || true
        sed -i '/# Cadre/d' "$rc" 2>/dev/null || true
    fi
done
echo -e "${GREEN}[✓]${NC} Cleaned up shell configuration"

echo ""
echo -e "${BOLD}Cadre has been uninstalled.${NC}"
echo -e "Restart Claude Code to complete the removal."
echo ""
