name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case, not just the feature.
      placeholder: "I keep having to re-explain my project conventions every session"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like?
      placeholder: "An auto-loader that reads project conventions from a config file"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      placeholder: "I tried putting everything in CLAUDE.md but it gets too long"
    validations:
      required: false
